# Nombre de nuestro workflow
name: DoñaMariaDeploy

# Eventos que activan el workflow: cuando haya un 'push' en la rama 'main'
on:
  push:
    branches: [ "main" ]

# Definición de los trabajos (jobs) a ejecutar
jobs:
  # Un trabajo llamado 'deploy'
  deploy:
    # El tipo de máquina virtual que usará GitHub Actions
    runs-on: ubuntu-latest
    
    # Permisos para que el workflow pueda escribir en el repositorio y desplegar
    permissions:
      contents: write
      pages: write
      id-token: write

    # Lista de pasos a ejecutar
    steps:
      # 1. Clona el código de tu repositorio en la máquina virtual
      - name: Obtener el código
        uses: actions/checkout@v4

      # 2. Despliega el sitio usando la acción oficial
      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Usa el token automático que GitHub genera
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # La carpeta donde están los archivos de tu sitio
          publish_dir: ./
